/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreLocationRouteImport } from './routes/store-location'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StoreLocationRoute = StoreLocationRouteImport.update({
  id: '/store-location',
  path: '/store-location',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/menu': typeof MenuRoute
  '/promo': typeof PromoRoute
  '/service': typeof ServiceRoute
  '/store-location': typeof StoreLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/menu': typeof MenuRoute
  '/promo': typeof PromoRoute
  '/service': typeof ServiceRoute
  '/store-location': typeof StoreLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/menu': typeof MenuRoute
  '/promo': typeof PromoRoute
  '/service': typeof ServiceRoute
  '/store-location': typeof StoreLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/menu' | '/promo' | '/service' | '/store-location'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/menu' | '/promo' | '/service' | '/store-location'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/menu'
    | '/promo'
    | '/service'
    | '/store-location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MenuRoute: typeof MenuRoute
  PromoRoute: typeof PromoRoute
  ServiceRoute: typeof ServiceRoute
  StoreLocationRoute: typeof StoreLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-location': {
      id: '/store-location'
      path: '/store-location'
      fullPath: '/store-location'
      preLoaderRoute: typeof StoreLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MenuRoute: MenuRoute,
  PromoRoute: PromoRoute,
  ServiceRoute: ServiceRoute,
  StoreLocationRoute: StoreLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
